/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.math.BigDecimal;
import model.Costume;
import service.CostumeService;
import util.AppConstants;
import util.AppLogger;
import util.CurrentUserSession;

/**
 *
 * @author ASUS
 */
public class Costume extends javax.swing.JFrame {

    /**
     * Creates new form Costume
     */
    public Costume() {
        
        this.setTitle("Aplikasi Manajemen Penyewaan Kostum");
        setIcon();
        
        initComponents();
        TampilkanKostum();
        IDKostumtxt.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Connection Con = null;
    Statement  St = null;
    ResultSet Rs = null;
    
    private void TampilkanKostum(){
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    
    try{
        conn = DatabaseManager.getInstance().getConnection();
        String query = "SELECT IDKostum as 'ID Kostum', NamaKarakter as 'Nama Karakter', " +
                      "AsalKarakter as 'Asal Karakter', Ukuran, Stok, Harga FROM Kostum";
        pstmt = conn.prepareStatement(query);
        rs = pstmt.executeQuery();
        Kostumtb.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(SQLException e){
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memuat data kostum.");
        System.err.println("Database error in TampilkanKostum: " + e.getMessage());
    }finally{
        DatabaseManager.closeResources(conn, pstmt, rs);
    }}
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Clearbtn = new javax.swing.JButton();
        AslKaraktertxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Ukurantxt = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        IDKostumtxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Hargatxt = new javax.swing.JTextField();
        Savebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Delettebtn = new javax.swing.JButton();
        NmKaraktertxt = new javax.swing.JTextField();
        Editbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Kostumtb = new javax.swing.JTable();
        Printbtn = new javax.swing.JButton();
        Stoktxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pelanggan");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sewa Kostum");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pengembalian");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Logout");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11)))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(21, 21, 21))
        );

        jPanel2.setBackground(new java.awt.Color(250, 248, 248));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Nama Karakter");

        Clearbtn.setBackground(new java.awt.Color(0, 153, 204));
        Clearbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        Clearbtn.setText("Clear");
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });

        AslKaraktertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AslKaraktertxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Ukuran");

        Ukurantxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L", "XL", "ALL SIZE" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Stok");

        IDKostumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDKostumtxtActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setText("ID Kostum");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Harga");

        Hargatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargatxtActionPerformed(evt);
            }
        });

        Savebtn.setBackground(new java.awt.Color(0, 153, 204));
        Savebtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Savebtn.setForeground(new java.awt.Color(255, 255, 255));
        Savebtn.setText("Save");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Input Kostum");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Asal Karakter");

        Delettebtn.setBackground(new java.awt.Color(0, 153, 204));
        Delettebtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Delettebtn.setForeground(new java.awt.Color(255, 255, 255));
        Delettebtn.setText("Delete");
        Delettebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelettebtnActionPerformed(evt);
            }
        });

        NmKaraktertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NmKaraktertxtActionPerformed(evt);
            }
        });

        Editbtn.setBackground(new java.awt.Color(0, 153, 204));
        Editbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Editbtn.setForeground(new java.awt.Color(255, 255, 255));
        Editbtn.setText("Edit");
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Daftar Kostum");

        Kostumtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Kostum", "Nama Karakter", "Asal Karakter", "Ukuran", "Status", "Harga"
            }
        ));
        Kostumtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KostumtbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Kostumtb);

        Printbtn.setBackground(new java.awt.Color(0, 153, 204));
        Printbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Printbtn.setForeground(new java.awt.Color(255, 255, 255));
        Printbtn.setText("Print");
        Printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintbtnActionPerformed(evt);
            }
        });

        Stoktxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoktxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDKostumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NmKaraktertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Printbtn)
                        .addGap(342, 342, 342))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AslKaraktertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ukurantxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Stoktxt, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hargatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Savebtn)
                .addGap(23, 23, 23)
                .addComponent(Editbtn)
                .addGap(18, 18, 18)
                .addComponent(Delettebtn)
                .addGap(27, 27, 27)
                .addComponent(Clearbtn)
                .addGap(213, 213, 213))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hargatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stoktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ukurantxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NmKaraktertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AslKaraktertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDKostumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Savebtn)
                    .addComponent(Clearbtn)
                    .addComponent(Delettebtn)
                    .addComponent(Editbtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Printbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NmKaraktertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NmKaraktertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NmKaraktertxtActionPerformed

    private void AslKaraktertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AslKaraktertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AslKaraktertxtActionPerformed

    private void HargatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargatxtActionPerformed

    private void clear(){
        IDKostumtxt.setText("");
        NmKaraktertxt.setText("");
        AslKaraktertxt.setText("");
        Ukurantxt.setSelectedIndex(0);
        //Statustxt.setSelectedIndex(0);
        Stoktxt.setText("");
        Hargatxt.setText("");
    }
    
    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_ClearbtnActionPerformed

    private void IDKostumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDKostumtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDKostumtxtActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        try {
            // Validate session
            CurrentUserSession.validateSession();
            
            // Input validation
            if (NmKaraktertxt.getText().trim().isEmpty() || 
                AslKaraktertxt.getText().trim().isEmpty() || 
                Ukurantxt.getSelectedIndex() == -1 || 
                Stoktxt.getText().trim().isEmpty() || 
                Hargatxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, AppConstants.ErrorMessages.REQUIRED_FIELD);
                return;
            }
            
            // Validate numeric inputs
            int stock;
            BigDecimal price;
            try {
                stock = Integer.parseInt(Stoktxt.getText().trim());
                price = new BigDecimal(Hargatxt.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Stok dan Harga harus berupa angka yang valid");
                return;
            }
            
            // Use CostumeService to create costume
            model.Costume newCostume = CostumeService.getInstance().createCostume(
                NmKaraktertxt.getText().trim(),
                AslKaraktertxt.getText().trim(),
                Ukurantxt.getSelectedItem().toString(),
                stock,
                price
            );
            
            if (newCostume != null) {
                JOptionPane.showMessageDialog(this, AppConstants.SuccessMessages.DATA_SAVED);
                TampilkanKostum();
                clear();
                
                // Log user action
                AppLogger.logUserAction(CurrentUserSession.getCurrentUsername(), 
                                      AppConstants.Actions.CREATE, "Costume", 
                                      String.valueOf(newCostume.getCostumeId()), 
                                      "Added new costume: " + newCostume.getCharacterName());
            } else {
                JOptionPane.showMessageDialog(this, AppConstants.ErrorMessages.DB_OPERATION_FAILED);
            }
            
        } catch (CurrentUserSession.SessionExpiredException e) {
            JOptionPane.showMessageDialog(this, "Sesi telah berakhir. Silakan login kembali.");
            new Login().setVisible(true);
            this.dispose();
        } catch (Exception e) {
            AppLogger.logError("Error in SavebtnActionPerformed", e);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data kostum.");
        }
        
    }//GEN-LAST:event_SavebtnActionPerformed

    private void DelettebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelettebtnActionPerformed
        if (IDKostumtxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Kostum yang ingin dihapus");
            return;
        }
        
        int confirmation = JOptionPane.showConfirmDialog(
            this, 
            "Apakah Anda Yakin Ingin Menghapus Kostum ini?", 
            "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        
        if (confirmation != JOptionPane.YES_OPTION) {
            return;
        }
        
        Connection conn = null;
        PreparedStatement pstmt = null;
        
        try{
            conn = DatabaseManager.getInstance().getConnection();
            String query = "DELETE FROM kostum WHERE IDKostum = ?";
            pstmt = conn.prepareStatement(query);
            pstmt.setInt(1, Integer.parseInt(IDKostumtxt.getText().trim()));
            
            int rowsAffected = pstmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Kostum Berhasil Dihapus");
                TampilkanKostum();
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Kostum tidak ditemukan atau sudah terhapus");
            }
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus kostum. Mungkin kostum sedang digunakan.");
            System.err.println("Database error in Delete: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Kostum tidak valid");
        } finally {
            DatabaseManager.closeResources(conn, pstmt, null);
        }//GEN-LAST:event_DelettebtnActionPerformed
    }
    
    private void KostumtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KostumtbMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Kostumtb.getModel();
        int Index = Kostumtb.getSelectedRow();
        IDKostumtxt.setText(model.getValueAt(Index, 0).toString());
        NmKaraktertxt.setText(model.getValueAt(Index, 1).toString());
        AslKaraktertxt.setText(model.getValueAt(Index, 2).toString());
        Ukurantxt.setSelectedItem(model.getValueAt(Index, 3).toString());
        //Statustxt.setSelectedItem(model.getValueAt(Index, 4).toString());
        Stoktxt.setText(model.getValueAt(Index, 4).toString());
        Hargatxt.setText(model.getValueAt(Index, 5).toString());
    }//GEN-LAST:event_KostumtbMouseClicked

    private void EditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbtnActionPerformed
        // Input validation
        if (IDKostumtxt.getText().trim().isEmpty() || 
            NmKaraktertxt.getText().trim().isEmpty() || 
            AslKaraktertxt.getText().trim().isEmpty() || 
            Ukurantxt.getSelectedIndex() == -1 || 
            Stoktxt.getText().trim().isEmpty() || 
            Hargatxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Kostum yang ingin diubah dan lengkapi semua data");
            return;
        }
        
        // Validate numeric inputs
        try {
            Integer.parseInt(Stoktxt.getText().trim());
            Integer.parseInt(Hargatxt.getText().trim());
            Integer.parseInt(IDKostumtxt.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID, Stok dan Harga harus berupa angka yang valid");
            return;
        }
        
        Connection conn = null;
        PreparedStatement pstmt = null;
        
        try{
            conn = DatabaseManager.getInstance().getConnection();
            String query = "UPDATE Kostum SET NamaKarakter=?, AsalKarakter=?, Ukuran=?, Stok=?, Harga=? WHERE IDKostum=?";
            pstmt = conn.prepareStatement(query);
            
            pstmt.setString(1, NmKaraktertxt.getText().trim());
            pstmt.setString(2, AslKaraktertxt.getText().trim());
            pstmt.setString(3, Ukurantxt.getSelectedItem().toString());
            pstmt.setInt(4, Integer.parseInt(Stoktxt.getText().trim()));
            pstmt.setInt(5, Integer.parseInt(Hargatxt.getText().trim()));
            pstmt.setInt(6, Integer.parseInt(IDKostumtxt.getText().trim()));
            
            int rowsAffected = pstmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Kostum Berhasil Diubah");
                TampilkanKostum();
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Kostum tidak ditemukan");
            }
        } catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengubah data kostum.");
            System.err.println("Database error in Edit: " + e.getMessage());
        } finally {
            DatabaseManager.closeResources(conn, pstmt, null);
        }
    }//GEN-LAST:event_EditbtnActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new Pelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new SewaKostum().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new Pengembalian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void PrintbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintbtnActionPerformed
        // TODO add your handling code here:
        try{
            Kostumtb.print();
        }catch(Exception e){

        }
    }//GEN-LAST:event_PrintbtnActionPerformed

    private void StoktxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoktxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StoktxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Costume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Costume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Costume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Costume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Costume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AslKaraktertxt;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JButton Delettebtn;
    private javax.swing.JButton Editbtn;
    private javax.swing.JTextField Hargatxt;
    private javax.swing.JTextField IDKostumtxt;
    private javax.swing.JTable Kostumtb;
    private javax.swing.JTextField NmKaraktertxt;
    private javax.swing.JButton Printbtn;
    private javax.swing.JButton Savebtn;
    private javax.swing.JTextField Stoktxt;
    private javax.swing.JComboBox<String> Ukurantxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Gambar/logo.png")));
    }
}
