/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class Pengembalian extends javax.swing.JFrame {

    /**
     * Creates new form Pengembalian
     */
    public Pengembalian() {
        
        this.setTitle("Aplikasi Manajemen Penyewaan Kostum");
        setIcon();
        
        initComponents();
        TampilkanRentalan();
        TampilkanSelesai();
        NamaKtxt.setEditable(false);
        NamaPtxt.setEditable(false);
        IDReturntxt.setEditable(false);
        IDRtxt.setEditable(false);
        Jumlahtxt.setEditable(false);
        //IDRtxt.setEditable(false);
        //Selesaitb.setEditable(false);
        Terlambattxt.setText("0");
        Dendatxt.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    Connection Con = null;
    Statement  St = null;
    ResultSet Rs = null;
    
private void clear(){
        IDReturntxt.setText("");
        IDKtxt.setText("");
        NamaKtxt.setText("");
        NamaPtxt.setText("");
        Jumlahtxt.setText("");
        Terlambattxt.setText("0");
        Dendatxt.setText("0");
        PDendatxt.setSelectedIndex(0);
        EKembalitxt.setSelectedIndex(0);
        RKembalitxt.setText("");
    }
    
    private void updatekostum(){
        try{
        Con = DriverManager.getConnection("jdbc:mysql://localhost/rental_cosplay","root","");
        //String statusKostum = "Tersedia";
        String query = "update kostum set Stok = Stok+ " + Jumlahtxt.getText() + " where IDKostum= " + IDKtxt.getText();
        Statement Add = Con.createStatement();
        Add.executeUpdate(query);

        //JOptionPane.showMessageDialog(this, "Kostum Berhasil Diupdate");
        } catch (Exception e){
            e.printStackTrace();
        }
        }
    
    //int ID;
    
    private void HapusRentalan(){
    try{
        Con = DriverManager.getConnection("jdbc:mysql://localhost/rental_cosplay","root","");
        String query = "Delete from rental where IDrent = " + IDRtxt.getText();
        Statement Add = Con.createStatement();
        Add.executeUpdate(query);
        TampilkanRentalan();
        //JOptionPane.showMessageDialog(this, "Kostum Berhasil Dikembalikan dan terhapus dari daftar kostum yang direntalkan");
        } catch (Exception e){
            e.printStackTrace();
        }
           
        
    }
    
    private void TampilkanRentalan(){
    try{
    
    Con = DriverManager.getConnection("jdbc:mysql://localhost/rental_cosplay","root","");
    St = Con.createStatement();
    Rs = St.executeQuery("select IDRent as 'ID Rent', IDKostum as 'ID Kostum', NamaPelanggan as 'Nama Pelanggan', NamaKarakter as 'Nama Karakter', Jumlah, TanggalPeminjaman as 'Tanggal Peminjaman', TanggalPengembalian as 'Batas Waktu', BiayaRental as 'Biaya Rental', Ekspedisi, Resi  from rental");
    Booktb.setModel(DbUtils.resultSetToTableModel(Rs));
    }catch(SQLException e){
        e.printStackTrace();
    }}
    
    private void TampilkanSelesai(){
    try{
    
    Con = DriverManager.getConnection("jdbc:mysql://localhost/rental_cosplay","root","");
    St = Con.createStatement();
    Rs = St.executeQuery("select IDPengembalian as 'ID Return', IDKostum as 'ID Kostum', NamaPelanggan as 'Nama Pelanggan', NamaKarakter as 'Nama Karakter', Jumlah, Keterlambatan, Denda, PembayaranDenda as 'Pembayaran Denda', EkspedisiPengembalian as 'Ekspedisi Pengembalian', ResiPengembalian as 'Resi Pengembalian' from pengembalian");
    Selesaitb.setModel(DbUtils.resultSetToTableModel(Rs));
    }catch(SQLException e){
        e.printStackTrace();
    }}    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Dendatxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        NamaKtxt = new javax.swing.JTextField();
        EKembalitxt = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Editbtn = new javax.swing.JButton();
        RKembalitxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Returnbtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Jumlahtxt = new javax.swing.JTextField();
        Clearbtn = new javax.swing.JButton();
        IDRtxt = new javax.swing.JTextField();
        textlabel92 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NamaPtxt = new javax.swing.JTextField();
        textlabel91 = new javax.swing.JLabel();
        IDKtxt = new javax.swing.JTextField();
        Terlambattxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        PDendatxt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        IDReturntxt = new javax.swing.JTextField();
        textlabel90 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Booktb = new javax.swing.JTable();
        Printbtn = new javax.swing.JButton();
        jlabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Selesaitb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pelanggan");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kostum");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SewaKostum");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Logout");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(21, 21, 21))
        );

        jPanel2.setBackground(new java.awt.Color(250, 248, 248));

        Dendatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DendatxtActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setText("Ekpedisi Pengembalian");

        NamaKtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaKtxtActionPerformed(evt);
            }
        });

        EKembalitxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanpa Ekspedisi", "JNE", "JNT", "SiCepat", "Paxel", "GoSend", "Grab" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Keterlambatan");

        Editbtn.setBackground(new java.awt.Color(0, 153, 204));
        Editbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Editbtn.setForeground(new java.awt.Color(255, 255, 255));
        Editbtn.setText("Edit");
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbtnActionPerformed(evt);
            }
        });

        RKembalitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RKembalitxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Denda");

        Returnbtn.setBackground(new java.awt.Color(0, 153, 204));
        Returnbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Returnbtn.setForeground(new java.awt.Color(255, 255, 255));
        Returnbtn.setText("Return");
        Returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnbtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 204));
        jLabel16.setText("Jumlah");

        Jumlahtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahtxtActionPerformed(evt);
            }
        });

        Clearbtn.setBackground(new java.awt.Color(0, 153, 204));
        Clearbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        Clearbtn.setText("Clear");
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });

        IDRtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDRtxtActionPerformed(evt);
            }
        });

        textlabel92.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textlabel92.setForeground(new java.awt.Color(0, 102, 204));
        textlabel92.setText("ID Rent");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Nama Pelanggan");

        NamaPtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPtxtActionPerformed(evt);
            }
        });

        textlabel91.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textlabel91.setForeground(new java.awt.Color(0, 102, 204));
        textlabel91.setText("ID Return");

        IDKtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDKtxtActionPerformed(evt);
            }
        });

        Terlambattxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerlambattxtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 204));
        jLabel12.setText("Pembayaran Denda");

        PDendatxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Denda", "Sudah", "Belum" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Nama Karakter");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setText("Resi Pengembalian");

        IDReturntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDReturntxtActionPerformed(evt);
            }
        });

        textlabel90.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textlabel90.setForeground(new java.awt.Color(0, 102, 204));
        textlabel90.setText("ID Kostum");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 204));
        jLabel14.setText("Daftar Kostum Booked ");

        Booktb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Rent", "ID Kostum", "Nama Pelanggan", "Nama Karakter", "Jumlah", "Tanggal Peminjaman", "Tanggal Pengembalian", "Biaya"
            }
        ));
        Booktb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooktbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Booktb);

        Printbtn.setBackground(new java.awt.Color(0, 153, 204));
        Printbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Printbtn.setForeground(new java.awt.Color(255, 255, 255));
        Printbtn.setText("Print");
        Printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintbtnActionPerformed(evt);
            }
        });

        jlabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabel15.setForeground(new java.awt.Color(0, 102, 204));
        jlabel15.setText("Daftar Kostum Selesai Dikembalikan");

        Selesaitb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Return", "ID Kostum", "Nama Pelanggan", "Nama Karakter", "Jumlah", "Keterlambatan", "Denda", "Pembayaran Denda", "Ekspedisi Pengembalian", "Resi Pengembalian"
            }
        ));
        Selesaitb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelesaitbMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Selesaitb);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Returnbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Editbtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(Clearbtn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textlabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamaKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamaPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDReturntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jumlahtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textlabel90)
                                    .addComponent(IDKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textlabel92)
                                    .addComponent(IDRtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dendatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Terlambattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDendatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EKembalitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RKembalitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel15)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(370, 370, 370)
                                .addComponent(Printbtn)))
                        .addGap(31, 31, 31))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textlabel91)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDReturntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textlabel90)
                            .addComponent(textlabel92))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDRtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamaPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamaKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jumlahtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Terlambattxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dendatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PDendatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EKembalitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RKembalitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Editbtn)
                    .addComponent(Returnbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Clearbtn)
                .addGap(61, 61, 61))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Printbtn)
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IDReturntxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDReturntxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDReturntxtActionPerformed

    private void NamaKtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaKtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaKtxtActionPerformed

    private void RKembalitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RKembalitxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RKembalitxtActionPerformed

    //java.util.Date tglkembali;
    //java.sql.Date tglkmbl;
    
    private void ReturnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnbtnActionPerformed
        // TODO add your handling code here:
        if (IDKtxt.getText().isEmpty() || NamaKtxt.getText().isEmpty() || NamaPtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data yang Dimasukkan Tidak Lengkap");
        }else{

            try{
                //tglkembali = TanggalKembalitxt.getDate();
                //tglkmbl = new java.sql.Date(tglkembali.getTime());

                Con = DriverManager.getConnection("jdbc:mysql://localhost/rental_cosplay","root","");
                PreparedStatement add = Con.prepareStatement("insert into pengembalian (IDKostum, NamaKarakter, NamaPelanggan, Keterlambatan, Denda, PembayaranDenda, EkspedisiPengembalian, ResiPengembalian, Jumlah) values(?,?,?,?,?,?,?,?,?)");
                add.setInt(1,Integer.parseInt(IDKtxt.getText()));
                add.setString(2, NamaKtxt.getText());
                add.setString(3,NamaPtxt.getText());
                add.setInt(4,Integer.parseInt(Terlambattxt.getText()));
                //add.setDate(4, tglkmbl);
                //add.setInt(4, Integer.valueOf(Terlambattxt.getText()));
                //add.setInt(5 , denda);
                add.setInt(5,Integer.parseInt(Dendatxt.getText()));
                add.setString(6, PDendatxt.getSelectedItem().toString());
                add.setString(7, EKembalitxt.getSelectedItem().toString());
                add.setString(8, RKembalitxt.getText());
                add.setInt(9, Integer.parseInt(Jumlahtxt.getText()));
                
                int row = add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Kostum Telah Berhasil Dikembalikan");
                
                TampilkanSelesai();
                updatekostum();
                HapusRentalan();
                TampilkanRentalan();
                clear();
            } catch (Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_ReturnbtnActionPerformed

    private void PrintbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintbtnActionPerformed
        // TODO add your handling code here:
        try{
        Selesaitb.print();   
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_PrintbtnActionPerformed

    
    
    private void BooktbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooktbMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Booktb.getModel();
        int Index = Booktb.getSelectedRow();
        IDRtxt.setText(model.getValueAt(Index, 0).toString());
        IDKtxt.setText(model.getValueAt(Index, 1).toString());
        NamaPtxt.setText(model.getValueAt(Index, 2).toString());
        NamaKtxt.setText(model.getValueAt(Index, 3).toString());   
        Jumlahtxt.setText(model.getValueAt(Index, 4).toString());
        //cost = Integer.valueOf(model.getValueAt(Index, 5).toString());
    }//GEN-LAST:event_BooktbMouseClicked

    private void SelesaitbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelesaitbMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Selesaitb.getModel();
        int Index = Selesaitb.getSelectedRow();
        IDReturntxt.setText(model.getValueAt(Index, 0).toString());
        IDKtxt.setText(model.getValueAt(Index, 1).toString());
        NamaPtxt.setText(model.getValueAt(Index, 2).toString());
        NamaKtxt.setText(model.getValueAt(Index, 3).toString());
        
        Terlambattxt.setText(model.getValueAt(Index, 4).toString());
        Dendatxt.setText(model.getValueAt(Index, 5).toString());
        PDendatxt.setSelectedItem(model.getValueAt(Index, 6).toString());
        EKembalitxt.setSelectedItem(model.getValueAt(Index, 7).toString());
        RKembalitxt.setText(model.getValueAt(Index, 8).toString());
    }//GEN-LAST:event_SelesaitbMouseClicked

    //int cost = 0;
    //int denda;
    private void NamaPtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPtxtActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new Pelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new Costume().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new SewaKostum().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void IDKtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDKtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDKtxtActionPerformed

    private void TerlambattxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerlambattxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TerlambattxtActionPerformed

    private void DendatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DendatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DendatxtActionPerformed

    private void EditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbtnActionPerformed
        // TODO add your handling code here:
        if (IDReturntxt.getText().isEmpty() || IDKtxt.getText().isEmpty() || NamaKtxt.getText().isEmpty() || NamaPtxt.getText().isEmpty() || Jumlahtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data yang ingin diubah");
        }else{
        
        try{
        Con = DriverManager.getConnection("jdbc:mysql://localhost/rental_cosplay","root","");
        String ID = IDReturntxt.getText();
        String query = "Update pengembalian set NamaKarakter= '" + NamaKtxt.getText() + "', NamaPelanggan='" + NamaPtxt.getText()+ "', Keterlambatan= " + Terlambattxt.getText()+ ", Denda= " + Dendatxt.getText()+ ", PembayaranDenda= '" + PDendatxt.getSelectedItem().toString() + "', EkspedisiPengembalian= '" + EKembalitxt.getSelectedItem().toString() + "', ResiPengembalian= '" + RKembalitxt.getText()+ "', Jumlah = " + Jumlahtxt.getText() + " where IDPengembalian= '" + ID + "'";
        Statement Add = Con.createStatement();
        Add.executeUpdate(query);
        TampilkanSelesai();
        
        clear();
        JOptionPane.showMessageDialog(this, "Kostum Berhasil Diubah");
        } catch (Exception e){
            e.printStackTrace();
        }
        }
        
    }//GEN-LAST:event_EditbtnActionPerformed

    private void JumlahtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahtxtActionPerformed

    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_ClearbtnActionPerformed

    private void IDRtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDRtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDRtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Booktb;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JTextField Dendatxt;
    private javax.swing.JComboBox<String> EKembalitxt;
    private javax.swing.JButton Editbtn;
    private javax.swing.JTextField IDKtxt;
    private javax.swing.JTextField IDReturntxt;
    private javax.swing.JTextField IDRtxt;
    private javax.swing.JTextField Jumlahtxt;
    private javax.swing.JTextField NamaKtxt;
    private javax.swing.JTextField NamaPtxt;
    private javax.swing.JComboBox<String> PDendatxt;
    private javax.swing.JButton Printbtn;
    private javax.swing.JTextField RKembalitxt;
    private javax.swing.JButton Returnbtn;
    private javax.swing.JTable Selesaitb;
    private javax.swing.JTextField Terlambattxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlabel15;
    private javax.swing.JLabel textlabel90;
    private javax.swing.JLabel textlabel91;
    private javax.swing.JLabel textlabel92;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Gambar/logo.png")));
    }
}
