/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class SewaKostum extends javax.swing.JFrame {

    /**
     * Creates new form SewaKostum
     */
    public SewaKostum() {
        
        this.setTitle("Aplikasi Manajemen Penyewaan Kostum");
        setIcon();
        
        initComponents();
        TampilkanKostum();
        getPelanggan();
        TampilkanRentalan();
        IDRtxt.setEditable(false);
        IDKtxt.setEditable(false);
        NamaKtxt.setEditable(false);
        HargaRtxt.setEditable(false);
        Area.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    Connection Con = null;
    Statement  St = null;
    ResultSet Rs = null;
    
    private void TampilkanKostum(){
    try{
    String StatusKostum = "0";
    Con = DriverManager.getConnection("jdbc:mysql://localhost/rental_cosplay","root","");
    St = Con.createStatement();
    Rs = St.executeQuery("select IDKostum as 'ID Kostum', NamaKarakter as 'Nama Karakter', AsalKarakter as 'Asal Karakter', Ukuran, Stok, Harga from Kostum where Stok != " +StatusKostum);
    Kostumtb.setModel(DbUtils.resultSetToTableModel(Rs));
    
    }catch(SQLException e){
        e.printStackTrace();
    }}
    private void TampilkanRentalan(){
    try{
    
    Con = DriverManager.getConnection("jdbc:mysql://localhost/rental_cosplay","root","");
    St = Con.createStatement();
    Rs = St.executeQuery("select IDRent as 'ID Rent', IDKostum as 'ID Kostum', NamaPelanggan as 'Nama Pelanggan', NamaKarakter as 'Nama Karakter', Jumlah, TanggalPeminjaman as 'Tanggal Peminjaman', TanggalPengembalian as 'Batas Waktu', BiayaRental as 'Total Biaya', Ekspedisi, Resi  from rental");
    Booktb.setModel(DbUtils.resultSetToTableModel(Rs));

    }catch(SQLException e){
        e.printStackTrace();
    }}
    
    private void getPelanggan(){
    try{
    Con = DriverManager.getConnection("jdbc:mysql://localhost/rental_cosplay","root","");
    St = Con.createStatement();
    String query = "select * from pelanggan";
    Rs = St.executeQuery(query);
    while (Rs.next()){
        String Pelanggan = Rs.getString("NamaPelanggan");
        NamaPtxt.addItem(Pelanggan);
        
        
    }
        
    }catch(Exception e){
        e.printStackTrace();
    }
    
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Editbtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Clearbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NoResitxt = new javax.swing.JTextField();
        Ekspedisitxt = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        IDKtxt = new javax.swing.JTextField();
        IDRtxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HargaRtxt = new javax.swing.JTextField();
        BiayaRtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Savebtn = new javax.swing.JButton();
        Jumlahtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TanggalPinjamtxt = new com.toedter.calendar.JDateChooser();
        TanggalKembalitxt = new com.toedter.calendar.JDateChooser();
        NamaPtxt = new javax.swing.JComboBox<>();
        NamaKtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Kostumtb = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Booktb = new javax.swing.JTable();
        Cetakbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();
        Totaltxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Printbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pelanggan");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kostum");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pengembalian");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Logout");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11)))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(21, 21, 21))
        );

        jPanel2.setBackground(new java.awt.Color(250, 248, 248));

        Editbtn.setBackground(new java.awt.Color(0, 153, 204));
        Editbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Editbtn.setForeground(new java.awt.Color(255, 255, 255));
        Editbtn.setText("Edit");
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 204));
        jLabel12.setText("Ekspedisi");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Nama Karakter");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setText("No.Resi");

        Clearbtn.setBackground(new java.awt.Color(0, 153, 204));
        Clearbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        Clearbtn.setText("Clear");
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Tanggal Peminjaman");

        NoResitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoResitxtActionPerformed(evt);
            }
        });

        Ekspedisitxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanpa Ekspedisi", "JNE", "JNT", "SiCepat", "Paxel", "GoSend", "Grab" }));
        Ekspedisitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkspedisitxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Batas Waktu");

        IDKtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDKtxtActionPerformed(evt);
            }
        });

        IDRtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDRtxtActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 204));
        jLabel16.setText("ID Kostum");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setText("ID Rent");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 204));
        jLabel17.setText("Harga :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("Biaya Pengiriman");

        HargaRtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaRtxtActionPerformed(evt);
            }
        });

        BiayaRtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiayaRtxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Sewa Kostum");

        Savebtn.setBackground(new java.awt.Color(0, 153, 204));
        Savebtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Savebtn.setForeground(new java.awt.Color(255, 255, 255));
        Savebtn.setText("Save");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });

        Jumlahtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahtxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Nama Pelanggan");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 204));
        jLabel18.setText("Jumlah");

        NamaPtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPtxtActionPerformed(evt);
            }
        });

        NamaKtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaKtxtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Daftar Kostum");

        Kostumtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Kostum", "Nama Karakter", "Asal Karakter", "Ukuran", "Stok", "Harga"
            }
        ));
        Kostumtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KostumtbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Kostumtb);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 204));
        jLabel14.setText("Daftar Kostum Booked ");

        Booktb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Rent", "ID Kostum", "Nama Pelanggan", "Nama Karakter", "Jumlah", "Tanggal Peminjaman", "Tanggal Pengembalian", "Biaya", "Ekspedisi", "Resi"
            }
        ));
        Booktb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooktbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Booktb);

        Cetakbtn.setBackground(new java.awt.Color(0, 153, 204));
        Cetakbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cetakbtn.setForeground(new java.awt.Color(255, 255, 255));
        Cetakbtn.setText("Cetak Transaksi");
        Cetakbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakbtnActionPerformed(evt);
            }
        });

        Area.setColumns(20);
        Area.setRows(5);
        jScrollPane3.setViewportView(Area);

        Totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotaltxtActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 204));
        jLabel19.setText("Total :");

        Printbtn.setBackground(new java.awt.Color(0, 153, 204));
        Printbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Printbtn.setForeground(new java.awt.Color(255, 255, 255));
        Printbtn.setText("Print");
        Printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(Cetakbtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Printbtn)
                                .addGap(121, 121, 121))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(494, 494, 494)
                            .addComponent(Savebtn)
                            .addGap(18, 18, 18)
                            .addComponent(Editbtn)
                            .addGap(18, 18, 18)
                            .addComponent(Clearbtn))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(IDRtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(IDKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(NamaPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NamaKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Jumlahtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(35, 35, 35)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(TanggalPinjamtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(TanggalKembalitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(BiayaRtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Ekspedisitxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addGap(18, 18, 18)
                                            .addComponent(HargaRtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(16, 16, 16)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NoResitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NamaKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDKtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jumlahtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NamaPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDRtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BiayaRtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ekspedisitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NoResitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TanggalPinjamtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TanggalKembalitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Savebtn)
                                .addComponent(Editbtn)
                                .addComponent(Clearbtn))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(HargaRtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel16)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cetakbtn)
                    .addComponent(Printbtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaKtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaKtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaKtxtActionPerformed

    private void clear(){
        IDRtxt.setText("");
        IDKtxt.setText("");
        NamaKtxt.setText("");
        NamaPtxt.setSelectedIndex(0);
        BiayaRtxt.setText("");
        Ekspedisitxt.setSelectedIndex(0);
        NoResitxt.setText("");
        HargaRtxt.setText("");
        Jumlahtxt.setText("1");
        Totaltxt.setText("");
    }
    
    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_ClearbtnActionPerformed

    private void IDRtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDRtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDRtxtActionPerformed

    private void BiayaRtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiayaRtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiayaRtxtActionPerformed

    private void KostumtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KostumtbMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Kostumtb.getModel();
        int Index = Kostumtb.getSelectedRow();
        IDKtxt.setText(model.getValueAt(Index, 0).toString());
        NamaKtxt.setText(model.getValueAt(Index, 1).toString());
        HargaRtxt.setText(model.getValueAt(Index, 5).toString());
    }//GEN-LAST:event_KostumtbMouseClicked

    private void BooktbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooktbMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Booktb.getModel();
        int Index = Booktb.getSelectedRow();
        IDRtxt.setText(model.getValueAt(Index, 0).toString());
        IDKtxt.setText(model.getValueAt(Index, 1).toString());
        NamaPtxt.setSelectedItem(model.getValueAt(Index, 2).toString());
        NamaKtxt.setText(model.getValueAt(Index, 3).toString());
        Jumlahtxt.setText(model.getValueAt(Index, 4).toString());
        //TanggalPinjamtxt.setDate(model.getValueAt(Index, 3).toString());
        //Statustxt.setSelectedItem(model.getValueAt(Index, 4).toString());
        Totaltxt.setText(model.getValueAt(Index, 7).toString());
        Ekspedisitxt.setSelectedItem(model.getValueAt(Index, 8).toString());
        NoResitxt.setText(model.getValueAt(Index, 9).toString());
    }//GEN-LAST:event_BooktbMouseClicked

    private void CetakbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakbtnActionPerformed
        // TODO add your handling code here:

        
        tglpinjam = TanggalPinjamtxt.getDate();
        tglpnjm = new java.sql.Date(tglpinjam.getTime());
        tglkembali = TanggalKembalitxt.getDate();
        tglkmbl = new java.sql.Date(tglkembali.getTime());
        
        Area.setText("========================================\n");
        Area.setText(Area.getText()+"=                             Bukti Transaksi                               =\n");
        Area.setText(Area.getText()+"========================================\n");
        
        Date obj = new Date();
        String tanggal = obj.toString();
        
        Area.setText(Area.getText()+"\n"+"Tanggal Transaksi: "+ tanggal+ "\n\n");
        Area.setText(Area.getText()+"ID Rent: "+IDRtxt.getText()+"\n\n");
        Area.setText(Area.getText()+"ID Kostum: "+IDKtxt.getText()+"\n\n");
        Area.setText(Area.getText()+"Nama Pelanggan: "+NamaPtxt.getSelectedItem().toString()+"\n\n");
        Area.setText(Area.getText()+"Nama Karakter: "+NamaKtxt.getText()+"\n\n");
        Area.setText(Area.getText()+"Jumlah: "+Jumlahtxt.getText()+"\n\n");
        Area.setText(Area.getText()+"Tanggal Peminjaman : "+tglpnjm.toString()+"\n\n");
        Area.setText(Area.getText()+"Batas Pengembalian : "+tglkmbl.toString()+"\n\n");
        Area.setText(Area.getText()+"Total: "+Totaltxt.getText()+"\n\n");
        Area.setText(Area.getText()+"Ekspedisi: "+Ekspedisitxt.getSelectedItem().toString()+"\n\n");
        Area.setText(Area.getText()+"Resi: "+NoResitxt.getText()+"\n\n");
        
        
    }//GEN-LAST:event_CetakbtnActionPerformed
    
    private void updatekostum(){
        try{
        Con = DriverManager.getConnection("jdbc:mysql://localhost/rental_cosplay","root","");
        //String statusKostum = "Stok-Jumlah";
        String query = "update kostum set Stok = Stok - " + Jumlahtxt.getText() + " where IDKostum= " + IDKtxt.getText();
        Statement Add = Con.createStatement();
        Add.executeUpdate(query);
        TampilkanKostum();
        clear();
        JOptionPane.showMessageDialog(this, "Kostum Berhasil Diupdate");
        } catch (Exception e){
            e.printStackTrace();
        }
        }

        
    
    
    java.util.Date tglpinjam, tglkembali;
    java.sql.Date tglpnjm,tglkmbl;
    //java.sql.Date tglpnjm,tglkmbl;    
        
    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        // TODO add your handling code here:
        if (NamaKtxt.getText().isEmpty() || NamaPtxt.getSelectedIndex()==-1 || BiayaRtxt.getText().isEmpty() || Jumlahtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data yang Dimasukkan Tidak Lengkap");
        }else{
            
        try{
            tglpinjam = TanggalPinjamtxt.getDate();
            tglpnjm = new java.sql.Date(tglpinjam.getTime());
            tglkembali = TanggalKembalitxt.getDate();
            tglkmbl = new java.sql.Date(tglkembali.getTime());
            
            int total;
            total = (Integer.parseInt(Jumlahtxt.getText())*Integer.parseInt(HargaRtxt.getText()) + Integer.parseInt(BiayaRtxt.getText()));
            
            Con = DriverManager.getConnection("jdbc:mysql://localhost/rental_cosplay","root","");
            PreparedStatement add = Con.prepareStatement("insert into rental (IDKostum, NamaKarakter, NamaPelanggan, TanggalPeminjaman, TanggalPengembalian, BiayaRental, Ekspedisi, Resi, Jumlah) values(?,?,?,?,?,?,?,?,?)");
            add.setInt(1, Integer.parseInt(IDKtxt.getText()));
            add.setString(2, NamaKtxt.getText());
            add.setString(3, NamaPtxt.getSelectedItem().toString());
            add.setDate(4, tglpnjm);
            add.setDate(5, tglkmbl);
            add.setInt(6, total);
            add.setString(7, Ekspedisitxt.getSelectedItem().toString());
            add.setString(8, NoResitxt.getText());
            add.setInt(9, Integer.parseInt(Jumlahtxt.getText()));
        int row = add.executeUpdate();
        JOptionPane.showMessageDialog(this, "Kostum Berhasil Direntalkan");
        TampilkanRentalan();
        updatekostum();
        TampilkanKostum();
        } catch (Exception e){
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_SavebtnActionPerformed

    private void EditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbtnActionPerformed
        // TODO add your handling code here:
         if (IDRtxt.getText().isEmpty() || NamaKtxt.getText().isEmpty() || NamaPtxt.getSelectedIndex()==-1 || Totaltxt.getText().isEmpty()|| Jumlahtxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Rentalan yang Ingin Diubah");
        }else{
            tglpinjam = TanggalPinjamtxt.getDate();
            tglpnjm = new java.sql.Date(tglpinjam.getTime());
            tglkembali = TanggalKembalitxt.getDate();
            tglkmbl = new java.sql.Date(tglkembali.getTime());
        try{
            

            
            Con = DriverManager.getConnection("jdbc:mysql://localhost/rental_cosplay","root","");
            int ID = Integer.parseInt(IDRtxt.getText());
            String query = "Update rental set NamaKarakter= '" + NamaKtxt.getText() + "', NamaPelanggan='" + NamaPtxt.getSelectedItem().toString()+ "', TanggalPeminjaman= '" + tglpnjm+"', TanggalPengembalian= '" + tglkmbl + "', BiayaRental= " + Totaltxt.getText() + ", Ekspedisi= '" + Ekspedisitxt.getSelectedItem().toString() + "', Resi= '" + NoResitxt.getText() + "', Jumlah = " + Jumlahtxt.getText() + " where IDRent= '" + ID + "'";
            Statement Add = Con.createStatement();
            Add.executeUpdate(query);
            TampilkanRentalan();
            clear();
            JOptionPane.showMessageDialog(this, "Rentalan Berhasil Diubah");
        } catch (Exception e){
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_EditbtnActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new Pelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        new Costume().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        new Pengembalian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void NoResitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoResitxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoResitxtActionPerformed

    private void EkspedisitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkspedisitxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EkspedisitxtActionPerformed

    private void IDKtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDKtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDKtxtActionPerformed

    private void HargaRtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaRtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaRtxtActionPerformed

    private void NamaPtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPtxtActionPerformed

    private void JumlahtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahtxtActionPerformed

    private void TotaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotaltxtActionPerformed

    private void PrintbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintbtnActionPerformed
        // TODO add your handling code here:
        try{
        Area.print();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_PrintbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SewaKostum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SewaKostum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SewaKostum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SewaKostum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SewaKostum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area;
    private javax.swing.JTextField BiayaRtxt;
    private javax.swing.JTable Booktb;
    private javax.swing.JButton Cetakbtn;
    private javax.swing.JButton Clearbtn;
    private javax.swing.JButton Editbtn;
    private javax.swing.JComboBox<String> Ekspedisitxt;
    private javax.swing.JTextField HargaRtxt;
    private javax.swing.JTextField IDKtxt;
    private javax.swing.JTextField IDRtxt;
    private javax.swing.JTextField Jumlahtxt;
    private javax.swing.JTable Kostumtb;
    private javax.swing.JTextField NamaKtxt;
    private javax.swing.JComboBox<String> NamaPtxt;
    private javax.swing.JTextField NoResitxt;
    private javax.swing.JButton Printbtn;
    private javax.swing.JButton Savebtn;
    private com.toedter.calendar.JDateChooser TanggalKembalitxt;
    private com.toedter.calendar.JDateChooser TanggalPinjamtxt;
    private javax.swing.JTextField Totaltxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Gambar/logo.png")));
    }
}
